name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - uses: jdx/mise-action@v3

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Refresh Spec Summaries
        run: |
          python -m auto.doc collect-specs
          python -m auto.doc spec-guide

      - name: Install dependencies
        run: |
          sudo apt install graphviz

      - name: Generate Assets
        run: |
          pip install diagrams
          mise run diagrams

      # https://ler.quest/astro-pdf/configuring-puppeteer/
      - name: Install browsers for Puppeteer
        run: |
          bunx puppeteer browsers install
          sudo tee /etc/apparmor.d/chrome-dev-builds <<EOF
          abi <abi/4.0>,
          include <tunables/global>
          # default executable location for puppeteer
          profile chrome $HOME/.cache/puppeteer/chrome/*/chrome-linux64/chrome flags=(unconfined) {
              userns,
              # Site-specific additions and overrides. See local/README for details.
              include if exists <local/chrome>
          }
          # if you are installing other versions using the install option
          profile chrome-local $PWD/node_modules/.astro/chrome/*/chrome-linux64/chrome flags=(unconfined) {
              userns,
              # Site-specific additions and overrides. See local/README for details.
              include if exists <local/chrome>
          }
          EOF
          sudo apparmor_parser -r /etc/apparmor.d/chrome-dev-builds
          sudo service apparmor reload

      - name: Install, build, and upload your site
        uses: withastro/action@v3

      - name: Upload PDF Documentation
        uses: actions/upload-artifact@v3
        with:
          name: Kintsu-Documentation-PDFs
          path: |
            ./dist/*.pdf

      - name: Upload Kinstu specs yaml
        uses: actions/upload-artifact@v3
        with:
          name: Kintsu-Specs-JSON
          path: |
            ./auto/kintsu.yaml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
